/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.discovery_marc.hr_chat_box;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * User generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`User`")
@IdClass(UserId.class)
public class User implements Serializable {

    private Integer sapSiteNumber;
    private String nameLine2;
    private String userId;
    private String password;

    @Id
    @Column(name = "`SAP_Site_Number`", nullable = true, scale = 0, precision = 10)
    public Integer getSapSiteNumber() {
        return this.sapSiteNumber;
    }

    public void setSapSiteNumber(Integer sapSiteNumber) {
        this.sapSiteNumber = sapSiteNumber;
    }

    @Id
    @Column(name = "`Name_Line_2`", nullable = true, length = 31)
    public String getNameLine2() {
        return this.nameLine2;
    }

    public void setNameLine2(String nameLine2) {
        this.nameLine2 = nameLine2;
    }

    @Id
    @Column(name = "`User_ID`", nullable = true, length = 7)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Id
    @Column(name = "`Password`", nullable = true, length = 9)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User)) return false;
        final User user = (User) o;
        return Objects.equals(getSapSiteNumber(), user.getSapSiteNumber()) &&
                Objects.equals(getNameLine2(), user.getNameLine2()) &&
                Objects.equals(getUserId(), user.getUserId()) &&
                Objects.equals(getPassword(), user.getPassword());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSapSiteNumber(),
                getNameLine2(),
                getUserId(),
                getPassword());
    }
}

